import React, { useEffect, useState } from "react";
import { useDispatch, useSelector } from "react-redux";
import { fetchReports, createReport, fetchAnalyticsOverview } from "../../redux/Slices/ReportSlice";
import styles from "./Reports.module.css";

function Reports() {
  const dispatch = useDispatch();
  const { reports, loading, overview, overviewLoading, overviewError } = useSelector((state) => state.report);
  const [showForm, setShowForm] = useState(false);
  const [formData, setFormData] = useState({
    reportName: "",
    reportType: "Employee",
    description: "",
    generatedBy: "",
    startDate: "",
    endDate: "",
    format: "PDF",
  });

  useEffect(() => {
    dispatch(fetchReports());
    dispatch(fetchAnalyticsOverview());
  }, [dispatch]);

  const handleInputChange = (e) => {
    const { name, value } = e.target;
    setFormData({ ...formData, [name]: value });
  };

  const handleSubmit = (e) => {
    e.preventDefault();
    dispatch(createReport(formData));
    resetForm();
  };

  const resetForm = () => {
    setFormData({
      reportName: "",
      reportType: "Employee",
      description: "",
      generatedBy: "",
      startDate: "",
      endDate: "",
      format: "PDF",
    });
    setShowForm(false);
  };

  return (
    <div className={styles.container}>
      <h1>Reports & Analytics</h1>
      <button onClick={() => setShowForm(!showForm)} className={styles.addBtn}>
        {showForm ? "Cancel" : "Generate Report"}
      </button>

      <div className={styles.overviewGrid}>
        <div className={styles.card}>
          <h2>Total Employees</h2>
          <p>{overviewLoading ? "Loading..." : overview?.totalEmployees ?? "—"}</p>
        </div>
        <div className={styles.card}>
          <h2>Open Job Openings</h2>
          <p>{overviewLoading ? "Loading..." : overview?.activeJobOpenings ?? "—"}</p>
        </div>
        <div className={styles.card}>
          <h2>Pending Leave Requests</h2>
          <p>{overviewLoading ? "Loading..." : overview?.pendingLeaveRequests ?? "—"}</p>
        </div>
        <div className={styles.card}>
          <h2>Avg Attendance</h2>
          <p>{overviewLoading ? "Loading..." : overview?.attendance?.averageAttendance?.toFixed(1) ?? "—"}%</p>
        </div>
        <div className={styles.card}>
          <h2>Avg Performance</h2>
          <p>{overviewLoading ? "Loading..." : overview?.performance?.averageRating?.toFixed(1) ?? "—"}</p>
        </div>
      </div>

      {overviewError && <p className={styles.error}>{overviewError}</p>}

      {showForm && (
        <form onSubmit={handleSubmit} className={styles.form}>
          <input
            type="text"
            name="reportName"
            placeholder="Report Name"
            value={formData.reportName}
            onChange={handleInputChange}
            required
          />
          <select
            name="reportType"
            value={formData.reportType}
            onChange={handleInputChange}
          >
            <option value="Employee">Employee</option>
            <option value="Attendance">Attendance</option>
            <option value="Payroll">Payroll</option>
            <option value="Leave">Leave</option>
            <option value="Performance">Performance</option>
          </select>
          <textarea
            name="description"
            placeholder="Description"
            value={formData.description}
            onChange={handleInputChange}
          />
          <input
            type="text"
            name="generatedBy"
            placeholder="Generated By"
            value={formData.generatedBy}
            onChange={handleInputChange}
            required
          />
          <input
            type="date"
            name="startDate"
            value={formData.startDate}
            onChange={handleInputChange}
          />
          <input
            type="date"
            name="endDate"
            value={formData.endDate}
            onChange={handleInputChange}
          />
          <select
            name="format"
            value={formData.format}
            onChange={handleInputChange}
          >
            <option value="PDF">PDF</option>
            <option value="Excel">Excel</option>
            <option value="CSV">CSV</option>
          </select>
          <button type="submit">Generate</button>
        </form>
      )}

      {loading ? (
        <p>Loading...</p>
      ) : (
        <table className={styles.table}>
          <thead>
            <tr>
              <th>Report Name</th>
              <th>Type</th>
              <th>Generated By</th>
              <th>Generated Date</th>
              <th>Format</th>
              <th>Download</th>
            </tr>
          </thead>
          <tbody>
            {reports.map((report) => (
              <tr key={report._id}>
                <td>{report.reportName}</td>
                <td>{report.reportType}</td>
                <td>{report.generatedBy}</td>
                <td>{new Date(report.generatedDate).toLocaleDateString()}</td>
                <td>{report.format}</td>
                <td>
                  {report.fileUrl ? (
                    <a href={report.fileUrl} download className={styles.downloadBtn}>
                      Download
                    </a>
                  ) : (
                    <span>Processing...</span>
                  )}
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      )}
    </div>
  );
}

export default Reports;
